const path = require('path')

const mode = 'production'
const target = 'web'
const outputDir = 'dst'
const outputPath = path.resolve(__dirname, outputDir)
const outputFile = 'bundle.js'

module.exports = [
    {
        entry: './src/index.tsx',
        mode,
        target,
        module: {
            rules: [
                {
                    test: /\.tsx?$/,
                    use: 'ts-loader',
                },
                {
                    test: /\.css$/,
                    use: [
                        'style-loader',
                        {
                            loader: 'typings-for-css-modules-loader',
                            options: {
                                modules: true,
                                namedExport: true,
                                banner:
                                    '// generated by typings-for-css-modules-loader, edit CSS file instead',
                            },
                        },
                    ],
                },
            ],
        },
        resolve: {
            extensions: ['.tsx', '.ts', '.js'],
        },
        output: {
            path: outputPath,
            filename: 'bundle.js',
        },
    },
]
